services:
  # ========== API GATEWAY (NGINX) ==========
  nginx:
    build:
      context: ./nginx
      dockerfile: Dockerfile
    image: api-gateway
    container_name: api-gateway
    ports:
      - "80:80"
    environment:
      FRONTEND_ORIGIN: ${FRONTEND_ORIGIN}
    depends_on:
      - auth-service
      - file-service
      - link-service

  # ========== AUTH SERVICE ==========
  auth-service:
    build:
      context: ./auth-service
      dockerfile: Dockerfile
    image: cloudnest-auth-service
    container_name: auth-service
    ports:
      - "8080:8080"
    env_file:
      - .env.prod

  # ========== FILE SERVICE ==========
  file-service:
    build:
      context: ./file-service
      dockerfile: Dockerfile
    image: cloudnest-file-service
    container_name: file-service
    ports:
      - "8081:8081"
    env_file:
      - .env.prod
    depends_on:
      - redis

  # ========== LINK SERVICE ==========
  link-service:
    build:
      context: ./link-service
      dockerfile: Dockerfile
    image: cloudnest-link-service
    container_name: link-service
    ports:
      - "8082:8082"
    env_file:
      - .env.prod

  # ========= WORKER SERVICE =========
  worker-service:
    build:
      context: ./worker-service
      dockerfile: Dockerfile
    image: cloudnest-worker-service
    container_name: worker-service
    ports:
      - "8083:8083"
    env_file:
      - .env.prod
    depends_on:
      - redis
      - file-service

  # ========= REDIS QUEUE =========
  redis:
    image: redis:8.4-rc1-alpine3.22
    container_name: redis
    ports:
      - "6379:6379"
