services:
  # ========== API GATEWAY (NGINX) ==========
  nginx:
    build:
      context: ./nginx
      dockerfile: Dockerfile
    image: api-gateway
    container_name: api-gateway
    ports:
      - "80:80"
    environment:
      FRONTEND_ORIGIN: ${FRONTEND_ORIGIN}
    depends_on:
      - auth-service
      - file-service
      - link-service

  # ========== AUTH SERVICE ==========
  auth-service:
    build:
      context: ./auth-service
      dockerfile: Dockerfile
    image: cloudnest-auth-service
    container_name: auth-service
    ports:
      - "8080:8080"
    env_file:
      - .env
  
  # ========== FILE SERVICE ==========
  file-service:
    build:
      context: ./file-service
      dockerfile: Dockerfile
    image: cloudnest-file-service
    container_name: file-service
    ports:
      - "8081:8081"
    env_file:
      - .env
    depends_on:
      - minio

  # ========== LINK SERVICE ==========
  link-service:
    build:
      context: ./link-service
      dockerfile: Dockerfile
    image: cloudnest-link-service
    container_name: link-service
    ports:
      - "8082:8082"
    env_file:
      - .env
    
  # ========== MINIO ==========
  minio:
    image: minio/minio:RELEASE.2025-09-07T16-13-09Z
    container_name: minio
    command: server /data --console-address ":9001"
    ports:
      - "9000:9000"   # S3 API
      - "9001:9001"   # MinIO Console
    environment:
      MINIO_ROOT_USER: ${MINIO_ACCESS_KEY}
      MINIO_ROOT_PASSWORD: ${MINIO_SECRET_KEY}
    volumes:
      - minio_data:/data

volumes:
  minio_data: