services:
  # ========== API GATEWAY (NGINX) ==========
  nginx:
    build:
      context: ./nginx
      dockerfile: Dockerfile
    image: api-gateway
    container_name: api-gateway
    restart: always
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - /etc/letsencrypt/live/api-cloudnest.duckdns.org:/etc/letsencrypt/live/api-cloudnest.duckdns.org:ro
      - /etc/letsencrypt/archive:/etc/letsencrypt/archive:ro
      - /etc/letsencrypt/renewal:/etc/letsencrypt/renewal:ro
    env_file:
      - .env.prod
    depends_on:
    - auth-service
    - file-service
    - worker-service
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "2"

  # ========== AUTH SERVICE ==========
  auth-service:
    build:
      context: ./auth-service
      dockerfile: Dockerfile
    image: cloudnest-auth-service
    container_name: auth-service
    restart: always
    expose: 
      - "8080"
    env_file:
      - .env.prod
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "2"

  # ========== FILE SERVICE ==========
  file-service:
    build:
      context: ./file-service
      dockerfile: Dockerfile
    image: cloudnest-file-service
    container_name: file-service
    restart: always
    expose: 
      - "8081"
    env_file:
      - .env.prod
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "2"

  # ========= WORKER SERVICE =========
  worker-service:
    build:
      context: ./worker-service
      dockerfile: Dockerfile
    image: cloudnest-worker-service
    container_name: worker-service
    restart: always
    env_file:
      - .env.prod
    depends_on:
    - file-service
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "2"
  
  # ========= DOZZLE LOG VIEWER =========
  dozzle:
    image: amir20/dozzle:latest
    container_name: dozzle
    restart: always
    ports:
      - "9999:8080"
    environment:
      - DOZZLE_BASE=/dozzle
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
