services:
  # ========== API GATEWAY (NGINX) ==========
  nginx:
    build:
      context: ./nginx
      dockerfile: Dockerfile
    image: api-gateway
    container_name: api-gateway
    ports:
      - "80:80"
      - "443:443"
    volumes:
    - /etc/letsencrypt/live/api-cloudnest.duckdns.org:/etc/letsencrypt/live/api-cloudnest.duckdns.org:ro
    - /etc/letsencrypt/archive:/etc/letsencrypt/archive:ro
    - /etc/letsencrypt/renewal:/etc/letsencrypt/renewal:ro
    env_file:
      - .env.prod
    depends_on:
      - auth-service
      - file-service

  # ========== AUTH SERVICE ==========
  auth-service:
    build:
      context: ./auth-service
      dockerfile: Dockerfile
    image: cloudnest-auth-service
    container_name: auth-service
    ports:
      - "8080:8080"
    env_file:
      - .env.prod

  # ========== FILE SERVICE ==========
  file-service:
    build:
      context: ./file-service
      dockerfile: Dockerfile
    image: cloudnest-file-service
    container_name: file-service
    ports:
      - "8081:8081"
    env_file:
      - .env.prod

  # ========= WORKER SERVICE =========
  worker-service:
    build:
      context: ./worker-service
      dockerfile: Dockerfile
    image: cloudnest-worker-service
    container_name: worker-service
    ports:
      - "8083:8083"
    env_file:
      - .env.prod
    depends_on:
      - file-service
