spring:
  application:
    name: worker-service

  data:
    redis:
      host: redis
      port: 6379

logging:
  level:
    root: INFO
    "[com.example.worker_service]": DEBUG

minio:
  url: ${MINIO_PUBLIC_URL}
  access-key: ${MINIO_ACCESS_KEY}
  secret-key: ${MINIO_SECRET_KEY}
  bucket: ${MINIO_BUCKET}

file:
  service:
    url: http://file-service:8081
