spring:
  application:
    name: worker-service
  main:
    web-application-type: none
    lazy-initialization: true

  data:
    redis:
      url: ${REDIS_URL}

logging:
  level:
    root: INFO
    "[com.example.worker_service]": DEBUG

minio:
  url: ${MINIO_PUBLIC_URL}
  access-key: ${MINIO_ACCESS_KEY}
  secret-key: ${MINIO_SECRET_KEY}
  bucket: ${MINIO_BUCKET}
  region: ${MINIO_REGION}
  publicBaseUrl: ${PUBLIC_FILE_BASE_URL}

file:
  service:
    url: http://file-service:8081
